[tox]
envlist =
    ruff
    py{38,39,310,311}-dj42-cms311
    py{310,311}-dj50-cms4

skip_missing_interpreters=True

[bdist_wheel]
universal=1

[testenv]
deps =
    -r{toxinidir}/tests/requirements/base.txt
    dj42: Django>=4.2,<5
    dj50: Django>=5,<5.1
    cms311: django-cms>=3.11.1,<4
    cms4: django-cms>=4
commands =
    {envpython} --version
    {env:COMMAND:coverage} erase
    {env:COMMAND:coverage} run tests/settings.py
    {env:COMMAND:coverage} report

[testenv:ruff]
deps = ruff
commands = ruff check
skip_install = true
