name: Lint

on: [push]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: python -Im pip install --user ruff

      - name: Run ruff on djangocms-admin-style
        run: ruff check --output-format=github djangocms_admin_style

